### ISSUE TITLE
"What's the number in the nickname of the original creator of Minetest, minus 1"?

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [minetest/forum.minetest.net_template1#11]
I was asked "What's the number in the nickname of the original creator of Minetest, minus 1". How am I to know the answer to this? Not even Google is able to provide the answer.

I posted this question within here because 'http://github.com/minetest/minetest/issues/4089#issuecomment-217136365' demonstrated that I should within here rather than anywhere that is alternative.

**Comment by rubenwardy** [comment]
It's celeron55   (Perttu Ahola is his real name)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/minetest/forum.minetest.net_template1/issues/11#issuecomment-1028979231

@rubenwardy, I actually typed "celeron54" twice as mere estimation (because the senior administrator was probably the creator). It did not accept that.

**Comment by rubenwardy** [comment]
Sorry, it's the number in the name minus 1, so 54

**Comment by RokeJulianLockhart** [comment]
> https://github.com/minetest/forum.minetest.net_template1/issues/11#issuecomment-1029150234

Consequently, @rubenwardy, I am confident that this question is more disadvantageous than it is advantageous, because confusion during account creation is not ideal.

**Comment by dontfwiththestream** [comment]
This is an absurd question, if it wasnt for this thread I wouldn't have been able to find this information with a simple search engine query

**Comment by rubenwardy** [comment]
Yeah, this is a dumb question and doesn't even work

**Comment by HybridDog** [comment]
>  if it wasnt for this thread I wouldn't have been able to find this information with a simple search engine query

The search engine https://www.phind.com gives the information, but it references to this issue.

**Comment by muzammal254** [comment]
We often use YouTube for entertainment and learning extra knowledge. It is an important social media platform with a great audience as traffic. Due to some limitations in the Youtube app you have to use [YouTube Revanced.](https://revancedutube.pro/)  https://revancedutube.pro/

**Comment by muzammal254** [comment]
There are many graphics applications available online but[ Alight Motion Mod APK ](https://alightemotionapk.com/)2024 will give your videos and images a different glow. With it, You can create brilliant pieces of animation. https://alightemotionapk.com/

**Comment by muzammal254** [comment]
The[ Holy Quran](https://quranpak.pro/) is the matchless Kalaam [Word] of that Lord عَزَّوَجَلَّ Who is the only Deity, the only Creator and the real Lord of the entire universe. The blessed revelation began in the sacred month of Ramadan. You can read Holy Quran and islamic info from  https://quranpak.pro/
