### ISSUE TITLE
body_bg.png should be loaded over HTTPS

### ISSUE THREAD

**Issue by CraigyDavi** [minetest/forum.minetest.net_template1#7]
```
viewtopic.php:1 Mixed Content: The page at 'https://forum.minetest.net/viewtopic.php?t=7010' was loaded over HTTPS, but requested an insecure image 'http://minetest.net//lib/tpl/minetest3/images/body_bg.png'. This content should also be served over HTTPS.
viewtopic.php:1 Mixed Content: The page at 'https://forum.minetest.net/viewtopic.php?t=7010' was loaded over HTTPS, but requested an insecure image 'http://www.minetest.net//lib/tpl/minetest3/images/body_bg.png'. This content should also be served over HTTPS.
```

**Comment by proller** [comment]
wat ?

**Comment by est31** [comment]
Its a so called [mixed content warning](https://developer.mozilla.org/en-US/docs/Security/MixedContent). It can be "fixed" by changing [this line](https://github.com/minetest/forum.minetest.net_template1/blob/29aba24dbe5033f2ad345f8a6316a3ec56e4ef90/theme/stylesheet.css#L31), just first we need actually CA signed SSL certificates for minetest.net, the current cert is self-signed.

**Comment by nerzhul** [comment]
@est31 replace http:// by a relative path an problem disappear or a path starting by /

**Comment by est31** [comment]
minetest.net has no https certificate, so this won't work unfortunately.

**Comment by celeron55** [comment]
That file should probably be included in this repository so that it doesn't need to be accessed from the other site. I'll accept a PR that does this, or maybe I'll fix it myself at some point.

**Comment by celeron55** [comment]
eafcde3ad1c65173ebcba21f25dc25854e3ecbdb
